# -*- coding: utf-8 -*-
"""BigFish

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aivUDOmIHU3u5FcZ8p5OIVHZRG4qSWQd
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import joblib

# Step 1: Loading Data from CSV Files
pre_data = pd.read_csv('emails.csv', encoding='utf-8')

# Step 2: Combining Data
data = pd.concat([pre_data], ignore_index=True)

# Step 3: Preprocessing
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(data['email'])
y = data['label']

# Step 4: Training the Model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)

# Step 5: Evaluating the Model
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1 Score: {f1:.2f}')

# Using the model to make predictions
new_emails = ["Hi, Congratulations! You have been selected to receive a brand new iPhone 13 as part of our exclusive promotion. To claim your prize, call 09061239876 and use the claim code IPHONE13. This offer is valid for 24 hours only. Don't miss this chance to get your hands on the latest iPhone! Cheers, Promotions Team"]
X_new = vectorizer.transform(new_emails)
y_new_pred = model.predict(X_new)

# Print predictions
for email, label in zip(new_emails, y_new_pred):
    print(f'Email: "{email}" - Predicted Label: {label}')